### medicine_calendar
medicine_calendar:
  header:
    frame_id: "map"
  child_frame_id: "medicine_calendar"
  transform:
    translation:
      x: 0.267
      y: 0.648
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.695
      w: 0.718
