### medicine_calendar
medicine_calendar:
  header:
    frame_id: "map"
  child_frame_id: "medicine_calendar"
  transform:
    translation:
      x: 1.71
      y: -1.29
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: -0.713
      w: 0.7
