### medicine_calendar
medicine_calendar:
  header:
    frame_id: "map"
  child_frame_id: "medicine_calendar"
  transform:
    translation:
      x: 0.50
      y: 0.437
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.692
      w: 0.721

### living_room
living_room:
  header:
    frame_id: "map"
  child_frame_id: "living_room"
  transform:
    translation:
      x: -0.068
      y: -0.203
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: -0.0015
