### medicine_calendar
medicine_calendar:
  header:
    frame_id: "map"
  child_frame_id: "medicine_calendar"
  transform:
    translation:
      x: -0.1
      y: 2.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: -0.707
      w: 0.707
